/* Styles used with SCSS Mixin "pictos" at _tools.pictos.scss */
export type TPictoStyles =
  | "search"
  | "check"
  | "cross"
  | "plus"
  | "add"
  | "import"
  | "arrowCorner"
  | "trash"
  | "text"
  | "textCase"
  | "expandVertical"
  | "picture"
  | "video"
  | "attachment"
  | "dashboard"
  | "windowUpload"
  | "windowCancel"
  | "fileDouble"
  | "eye"
  | "printer"
  | "compteurDechets"
  | "close"
  | "history"
  | "edit"
  | "polygon";
