# Main Azure pipeline configuration file for MSD BO Static WebSite
name: MSD_FO_Site_$(Rev:rrr)

trigger:
  batch: true
  branches:
    include:
      - develop
      - feature/*

variables:
  - name: runCD
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  - group: fo_site_variables
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: CI tasks
    jobs:
      - template: pipelines/jobs/ci.yml

  - stage: Release
    displayName: Service update on Azure Cloud
    condition: and(eq(variables.runCD, 'true'), succeeded())
    jobs:
      - template: pipelines/jobs/release.yml
