# Main Azure pipeline configuration file for MSD BO Static WebSite
name: MSD_FO_Site_$(Rev:rrr)

trigger:
  batch: true
  branches:
    include:
      - develop
      - release/*

variables:
  - name: releaseDev
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}
  - name: releaseRec
    value: ${{ startsWith(variables['Build.SourceBranch'], 'refs/heads/release') }}

parameters:
  - name: az_env
    displayName: Instance à livrer
    type: string
    default: smile
    values:
      - smile
      - production

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: CI tasks
    jobs:
      - template: azure-pipelines/build.yml
        ${{ if eq(variables.releaseRec, 'true') }}:
          parameters:
            env: rec

  - stage: Release
    displayName: Service update on Azure Cloud
    condition: and(succeeded(),or(eq(variables.releaseDev, 'true'),eq(variables.releaseRec, 'true')))
    variables:
      - ${{ if eq(variables.releaseDev, 'true') }}:
          - group: fo_site_variables_dev
          - name: env
            value: dev
      - ${{ if eq(variables.releaseRec, 'true') }}:
          - group: fo_site_variables_rec
          - name: env
            value: rec
    jobs:
      - template: azure-pipelines/release.yml
        parameters:
          env: ${{ variables.env }}
          ${{ if eq(variables.releaseRec, 'true') }}:
            instance: ${{ parameters.az_env }}
          ${{ else }}:
            instance: "production"
