name: $(BuildID)

trigger:
  batch: true
  branches:
    - develop
    - feature/69_dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: "build"
    variables:
      CI: true
    jobs:
      - job: BuildMSDFront
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "14.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "custom"
              customCommand: "install -g gatsby-cli"
            displayName: "Install gatsby-cli"

          - task: Npm@1
            inputs:
              command: "install"
            displayName: "Install dependencies"

          - template: test-and-coverage.yml

          - task: Npm@1
            inputs:
              command: "custom"
              customCommand: "run build"
            displayName: "Gatsby build"

          - task: CopyFiles@2
            inputs:
              SourceFolder: "public"
              Contents: "**"
              TargetFolder: $(Build.ArtifactStagingDirectory)
              CleanTargetFolder: true
            displayName: "Copy public folder"

          - publish: $(Build.ArtifactStagingDirectory)
            displayName: "Save artifact for later use"
            artifact: BuildMSDFront
